#!/bin/sh
Green='\033[0;32m'
Color_off='\033[0m'
Red='\033[0;31m'

case "$1" in
	start)
		printf "Starting dnsd "
#		sleep 10
		/usr/bin/dnsd -d -c /etc/dnsd.conf
		echo "nameserver 0.0.0.0" > /etc/resolv.conf
		if [[ "$?" == "0" ]]; then
			echo "nameserver 0.0.0.0" > /etc/resolv.conf
			echo $(pgrep dnsd) > /var/run/dnsd.pid
			printf "[$Green OK $Color_off]\n"
		else
			printf "[$Red ERR $Color_off]\n"
		fi
		;;
	stop)
		printf "Stopping dnsd "
		kill $(cat /var/run/dnsd.pid) &> /dev/null 
		rm /var/run/dnsd.pid
		if [[ "$?" == "0" ]]; then
			printf "[$Green OK $Color_off]\n"
		else
			printf "[$Red ERR $Color_off]\n"
		fi
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "dnsmasq init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
