#!/bin/sh

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Starting fptd "
		tcpsvd -vE 0.0.0.0 21 ftpd -w -S -A $(cat /etc/openrouter/ftppath) &>/dev/null &
		echo $! > /var/run/ftpd.pid
		check $?
		;;
	stop)
		notify "Stopping ftpd "
		kill $(cat /var/run/ftpd.pid)
		killall ftpd
		rm /var/run/ftpd.pid
		check $?
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "ftpd init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
