#!/bin/sh

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Setting up hostname "
		/bin/hostname -F /etc/hostname
		check $?
		;;
    stop)
        ;;
    *)
        echo "Hostname init script usage: $0 {start}"
        return 1
esac
return $?
