#!/bin/sh

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Starting httpd "
		httpd -h /srv/www &> /dev/null
		check $?
		;;
	stop)
		notify "Stopping httpd "
		killall httpd
		#kill $(cat /var/run/httpd.pid)
		#rm /var/run/httpd.pid
		check $?
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "httpd init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
