#!/bin/sh
Green='\033[0;32m'
Color_off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Starting klogd "
		klogd
		check $?
		;;
	stop)
		notify "Stopping klogd "
		if [ -f /var/run/klogd.pid ]; then
			kill $(cat /var/run/klogd.pid)
			check $?
			rm /var/run/klogd.pid &> /dev/null
		else
			notify "[$Red Klogd is not running $Color_off]\n"
		fi
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "klogd init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
