#!/bin/sh
Green='\033[0;32m'
Color_Off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Starting networking "
		/usr/bin/ifup -a &>/dev/null &
		echo $! > /var/run/networking.pid
		check $?
		;;
	stop)
		notify "Stopping networking "
		/usr/bin/ifdown -a
		rm /var/run/networking.pid
		check $?
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "networking init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
