#!/bin/sh
Green='\033[0;32m'
Color_off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Starting nginx "
		nginx
		check $?
		;;
	stop)
		notify "Stopping nginx "
		nginx -s stop
		check $?
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "nginx init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
