#!/bin/sh
Green='\033[0;32m'
Color_Off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
        start)
                notify "Starting openrouter software "
                cd /srv/ftpd/auth_service_router/bin && ./auth_service &> /dev/null &
                cd /srv/ftpd/openrouter_adminpanel/bin && ./openrouter &> /dev/null &
                check $?
                ;;
        stop)
                notify "Stopping openrouter software "
                killall openrouter
                killall auth_service
                check $?
                ;;
        restart|reload)
                "$0" stop
                "$0" start
                ;;
        *)
                echo "httpd init script usage: $0 {start|stop|restart}"
                return 1
esac
return $?