#!/bin/sh

. /etc/init.d/init-functions

case "$1" in
        start)
                notify "Starting openrouter software "
                cd /srv/ftpd/auth_service_router/bin && ./auth_service &> /dev/null &
                echo $! > /var/run/openrouterinit.pid
                cd /srv/ftpd/openrouter_adminpanel/bin && ./openrouter &> /dev/null &
                echo $! >> /var/run/openrouterinit.pid
                check $?
                ;;
        stop)
                notify "Stopping openrouter software "
                killall openrouter
                killall auth_service
                rm /var/run/openrouterinit.pid
                check $?
                ;;
        restart|reload)
                "$0" stop
                "$0" start
                ;;
        *)
                echo "httpd init script usage: $0 {start|stop|restart}"
                return 1
esac
return $?