#!/bin/sh
Green='\033[0;32m'
Color_off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Configuring swap "
		swapon -a
		check $?
		;;
	stop)
		notify "Stopping use swap "
		swapoff -a
        check $?
		;;
	restart|reload)
		"$0" stop
		"$0" start
		;;
	*)
		echo "swap init script usage: $0 {start|stop|restart}"
		return 1
esac
return $?
