#!/bin/sh

Green='\033[0;32m'
Color_Off='\033[0m'
Red='\033[0;31m'

. /etc/init.d/init-functions

case "$1" in
	start)
		notify "Setting up sysctl "
		sysctl -p &> /dev/null
		check $?
		;;
    stop)
        ;;
    *)
        echo "Sysctl init script usage: $0 {start}"
        return 1
esac
return $?
